<?php

/**
 * Implements hook_menu()
 */

function mlmta_cmf_tallies_menu() {
  
  
  $items = array( 
    'admin/tallies-mlmta-cmf-competitions' => array(
      'title' => 'MLMTA CMF registration tallies',
      'description' => 'Form to generate tallies',
      'access arguments' => array(
        'edit any pursuit entities'
      ),
      'page callback' => 'mlmta_dmf_tallies_page',
      'type' => MENU_CALLBACK,
    ),
  );
  return $items;
}

/** 
 * Callback
 */
function mlmta_dmf_tallies_page() {
  $options = array(
    'type' => 'Registration type',
    'field_piano_solo_level' => 'Level',
    'pursuit_preferred_time' => 'Preferred time',
    'field_grade' => 'Grade',
    'pursuit_group_tagged' => 'Group tagged',
  );
  
  $grouping_fields = array( // field => table passed to the submit handler
    'field_piano_solo_level' => 'field_data_field_piano_solo_level',
    'pursuit_preferred_time' => 'field_data_pursuit_preferred_time',
    'field_grade' => 'field_data_field_grade',
    'pursuit_group_tagged' => 'field_data_pursuit_group_tagged',
  );
  $output = drupal_get_form('pursuit_wizard_tallies_form', $options, $grouping_fields);

  return $output;
}
